@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;

'Since the beta syntax does not support placing the condition outside the
'diamond we place it as the true branch instead.

if () then ([command is data-modifying])
    if () then ([command is undo (redo)])
        :Add current state to redoHistory (undoHistory);
        :Set current state to last state in undoHistory (redoHistory);
        :Remove last state from undoHistory (redoHistory);
    else ([else])
        :Save current state to undoHistory;
        :Clear redoHistory;
        :Execute command;
    endif
else ([else])
    :Execute command;
endif
stop
@enduml
