@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor MODEL_COLOR
skinparam classBackgroundColor MODEL_COLOR

Package Model as ModelPackage <<Rectangle>>{
Class "<<interface>>\nReadOnlyPharmHub" as ReadOnlyPharmHub
Class "<<interface>>\nReadOnlyUserPrefs" as ReadOnlyUserPrefs
Class "<<interface>>\nModel" as Model
Class PharmHub
Class VersionedPharmHub
Class ModelManager
Class UserPrefs

Class UniquePersonList
Class MedicineList
Class OrderList
Class Person
Class Order
Class Medicine
}

Class HiddenOutside #FFFFFF
HiddenOutside ..> Model

PharmHub .up.|> ReadOnlyPharmHub
VersionedPharmHub -up-|> PharmHub

ModelManager .up.|> Model
Model .right.> ReadOnlyUserPrefs
Model .left.> ReadOnlyPharmHub
ModelManager --> "1" VersionedPharmHub
ModelManager -right-> "1" UserPrefs
UserPrefs .up.|> ReadOnlyUserPrefs

VersionedPharmHub *--> "1" UniquePersonList
VersionedPharmHub *--> "1" OrderList
VersionedPharmHub *--> "1" MedicineList
UniquePersonList --> "~* all" Person
OrderList --> "~* all" Order
MedicineList --> "~* all" Medicine

ModelManager -down---> "~* filtered" Medicine
ModelManager -down---> "~* filtered" Person
ModelManager -down---> "~* filtered" Order

OrderList -[hidden]right-> MedicineList


@enduml
