@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title Initial state

hide State1
hide State2
hide State3
hide State4
hide State5
hide State6

package UndoHistory {
}

package RedoHistory {
}

class Current as "<u>ab0:PharmHub</u>"

RedoHistory -[hidden]up-> UndoHistory

class Pointer as "Current State" #FFFFFF
Pointer -[hidden]up-> RedoHistory
Pointer -right-> Current
@end
