@startuml
!include style.puml
skinparam ClassFontColor #000000
skinparam ClassBorderColor #000000
skinparam ClassBackgroundColor #FFFFAA

title After command "add n/David"

package UndoHistory {
    class State1 as "<u>ab0:PharmHub</u>"
    class State2 as "<u>ab1:PharmHub</u>"

    State1 -[hidden]right-> State2
}

package RedoHistory {

}

RedoHistory -[hidden]up-> UndoHistory

class Current as "<u>ab2:PharmHub</u>"

class Pointer as "Current State" #FFFFFF
Pointer -[hidden]up-> RedoHistory

Pointer -right-> Current
@end
