@startuml
skin rose
skinparam ActivityFontSize 15
skinparam ArrowFontSize 12
start
:User executes command;
:Command is executed by LogicManager;
:CommandResult is returned to MainWindow;

if () then ([CommandResult has InfoObject])
    if () then ([InfoObject instanceof Person])
        :Create PersonDisplay;
        :Attach created PersonDisplay onto the InfoDisplay;
    elseif () then ([InfoObject instanceof Order])
        :Create OrderDisplay;
        :Attach created OrderDisplay onto the InfoDisplay;
    else ([else])
        :Throw RuntimeError;
        stop
    endif
else ([else])

endif
stop
@enduml
