@startuml
!include style.puml
skinparam ArrowFontStyle plain
skinparam sequenceReferenceBackgroundColor white

box Ui UI_COLOR_T1
participant ":MainWindow" as MainWindow UI_COLOR
-> MainWindow : executeCommand(viewp)
activate MainWindow

ref over MainWindow : execute command

MainWindow -> MainWindow : handleDisplayInfoObject(Person)
activate MainWindow

create ":PersonDisplay" as PersonDisplay UI_COLOR
MainWindow -> PersonDisplay : PersonDisplay(Person)
activate PersonDisplay

PersonDisplay -> MainWindow
deactivate PersonDisplay

participant ":InfoDisplayPlaceholder" as InfoDisplayPlaceholder UI_COLOR

MainWindow -> InfoDisplayPlaceholder : clear()
activate InfoDisplayPlaceholder

InfoDisplayPlaceholder -> MainWindow
deactivate InfoDisplayPlaceholder

MainWindow -> InfoDisplayPlaceholder : add(PersonDisplay)
activate InfoDisplayPlaceholder

InfoDisplayPlaceholder -> MainWindow
deactivate InfoDisplayPlaceholder

MainWindow -> MainWindow
deactivate MainWindow

<-- MainWindow : result
deactivate MainWindow



endbox

@enduml
